# cspell: ignore lcov erikyo tsdoc

name: Tests

on:
    push:
        branches:
            - master
env:
    NODE_OPTIONS: --test-reporter=spec --test-reporter-destination=stdout --test-reporter=lcov --test-reporter-destination=lcov.info
    IDF_PATH: ${{ github.workspace }}/esp-idf
    PARTITION_TABLE_SCRIPT_URL: https://raw.githubusercontent.com/espressif/esp-idf/refs/heads/master/components/partition_table/gen_esp32part.py

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            pages: write
        steps:
            - uses: actions/checkout@v6
            - run: npm install
            - run: pip install esp_idf_nvs_partition_gen
            - run: curl -L ${{ env.PARTITION_TABLE_SCRIPT_URL }} --create-dirs -o esp-idf/components/partition_table/gen_esp32part.py

            - uses: erikyo/tsdoc-action@v1
              with:
                source_dir: ./src
                output_dir: ./_site/docs
                tsconfig: ./lint/tsconfig_browser.json

            - run: cp -r ./examples ./_site/examples
            - run: cp -r ./src ./_site/src

            - run: npm test
            - run: mv ./coverage/lcov-report ./_site/coverage
              if: ${{ !cancelled() }}
            - run: npx lcov-badge2 coverage/lcov.info -l Coverage -o ./_site/coverage.svg
              if: ${{ !cancelled() }}
            - run: npm run lint
              if: ${{ !cancelled() }}

            - uses: actions/upload-pages-artifact@v4
              if: ${{ !cancelled() }}
            - uses: actions/deploy-pages@v4
              if: ${{ !cancelled() }}
